
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.util.ArrayList;


/**
 *
 * @author Paul KWofie
 */
public class RegisterationJPanel extends javax.swing.JPanel {

    private Business business;
    private StudentProfile student;
    private JPanel CardSequencePanel;
    
    

    public RegisterationJPanel() {
        initComponents();
    }
    
    /**
     * Creates new form RegisterationJPanel with business logic
     * @param business
     * @param student
     * @param cardPanel
     */
    public RegisterationJPanel(Business business, StudentProfile student, JPanel cardPanel) {
        this.business = business;
        this.student = student;
        this.CardSequencePanel = cardPanel;
        initComponents();
        populateStudentInfo();
        populateRegistrationTable(); 
    }


    private void populateStudentInfo() {
        if (student != null) {
            jLabel3.setText(student.getName()); // Student Name
            jLabel5.setText(student.getStudentId()); // Student ID
            jLabel7.setText(student.getMajor()); // Major
        }
    }
    
    private void populateRegistrationTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data
        
        if (student != null) {
            ArrayList<String> enrolledCourses = student.getCoursesEnrolled();
            
            if (enrolledCourses != null && !enrolledCourses.isEmpty()) {
                for (String courseCode : enrolledCourses) {

                    Object[] row = {
                        courseCode,
                        getCourseNameFromCode(courseCode),
                        getCourseCredits(courseCode),
                        "Registered",
                        "2025-01-15"
                    };
                    model.addRow(row);
                }
            } else {
                Object[][] sampleData = {
                    {"CS101", "Introduction to Computer Science", "3", "Registered", "2025-01-15"},
                    {"MATH201", "Calculus I", "4", "Registered", "2025-01-15"},
                    {"ENG101", "English Composition", "3", "Waitlisted", "2025-01-16"},
                    {"PHYS101", "Physics I", "4", "Registered", "2025-01-17"}
                };
                
                for (Object[] row : sampleData) {
                    model.addRow(row);
                }
            }
        }
    }

    private String getCourseNameFromCode(String courseCode) {
        // Simple mapping - in real system, query from database
        switch (courseCode) {
            case "CS101": return "Introduction to Computer Science";
            case "CS102": return "Data Structures";
            case "MATH201": return "Calculus I";
            case "ENG101": return "English Composition";
            case "PHYS101": return "Physics I";
            default: return "Course Name";
        }
    }
    

    private String getCourseCredits(String courseCode) {
        if (courseCode.startsWith("MATH") || courseCode.startsWith("PHYS")) {
            return "4";
        }
        return "3";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));

        jButton1.setText("<<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        jLabel1.setText("Registeration Status");

        jLabel5.setText("jLabel5");

        jLabel2.setText("Student Name:");

        jLabel7.setText("jLabel7");

        jLabel6.setText("Major:");

        jLabel4.setText("Student ID:");

        jLabel3.setText("jLabel3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name", "Credits", "Registeration Status", "Date Registered"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel8.setText("My Registeration Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (CardSequencePanel != null) {
            try {
                ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "StudentWorkArea");
            } catch (Exception e) {
                StudentWorkAreaJPanel studentWorkArea = new StudentWorkAreaJPanel(business, student, CardSequencePanel);
                CardSequencePanel.add("StudentWorkArea", studentWorkArea);
                ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "StudentWorkArea");
            }
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
