/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author Paul Kwofie
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {

    private Business business;
    private StudentProfile student;
    private JPanel CardSequencePanel;
    

    public GraduationAuditJPanel() {
        initComponents();
    }
    
    /**
     * Creates new form GraduationAuditJPanel with business logic
     * @param business
     * @param student
     * @param cardPanel
     */
    public GraduationAuditJPanel(Business business, StudentProfile student, JPanel cardPanel) {
        this.business = business;
        this.student = student;
        this.CardSequencePanel = cardPanel;
        initComponents();
        populateStudentData();
    }

    private void populateStudentData() {
        if (student != null) {
            jLabel3.setText(student.getName() != null ? student.getName() : "N/A");
            jLabel5.setText(student.getMajor() != null ? student.getMajor() : "N/A");
            
            int creditsCompleted = calculateCreditsCompleted();
            int creditsRequired = 120; // Standard requirement
            int creditsRemaining = creditsRequired - creditsCompleted;
            
            jLabel7.setText(String.valueOf(creditsCompleted));
            jLabel9.setText(String.valueOf(creditsRequired));
            jLabel11.setText(String.valueOf(creditsRemaining));
            
            jLabel13.setText(String.format("%.2f", student.getGPA()));

        }
    }
    

    private int calculateCreditsCompleted() {
        if (student == null || student.getCoursesEnrolled().isEmpty()) {
            return 0;
        }
        
        int totalCredits = 0;
        for (String courseCode : student.getCoursesEnrolled()) {
            if (courseCode.startsWith("MATH") || courseCode.startsWith("PHYS")) {
                totalCredits += 4;
            } else {
                totalCredits += 3;
            }
        }
        return totalCredits;
    }
    

    private String getGraduationStatus(int creditsRemaining) {
        if (creditsRemaining <= 0) {
            return "Ready to Graduate!";
        } else if (creditsRemaining <= 30) {
            return "On Track - Senior Year";
        } else if (creditsRemaining <= 60) {
            return "On Track - Junior Year";
        } else if (creditsRemaining <= 90) {
            return "On Track - Sophomore Year";
        } else {
            return "On Track - Freshman Year";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setText("<<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        jLabel1.setText("Graduation Audit");

        jLabel2.setText("Student Name:");

        jLabel3.setText("jLabel3");

        jLabel4.setText("Major:");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Credits Completed:");

        jLabel7.setText("jLabel7");

        jLabel8.setText("Credits Required");

        jLabel9.setText("jLabel9");

        jLabel10.setText("Credits Remaining;");

        jLabel11.setText("jLabel11");

        jLabel12.setText("Current GPA:");

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (CardSequencePanel != null) {
            ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "StudentWorkArea");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
