/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Business.Courses.Course;


/**
 *
 * @author yasminalmousa
 */
public class TranscriptJPanel extends javax.swing.JPanel {

    private Business business;
    private StudentProfile student;
    private JPanel CardSequencePanel;
    
    /**
     * Creates new form TranscriptJPanel
     */
    public TranscriptJPanel() {
        initComponents();
    }
    
    /**
     * Creates new form TranscriptJPanel with business logic
     * @param business
     * @param student
     * @param cardPanel
     */
    public TranscriptJPanel(Business business, StudentProfile student, JPanel cardPanel) {
        this.business = business;
        this.student = student;
        this.CardSequencePanel = cardPanel;
        initComponents();
        populateTranscriptData();
    }
    
    /**
     * Populate the transcript with student data
     */
    private void populateTranscriptData() {
        if (student != null) {
            // Populate student info labels
            jLabel3.setText(student.getName() != null ? student.getName() : "N/A");
            jLabel8.setText(student.getStudentId() != null ? student.getStudentId() : "N/A");
            jLabel5.setText(student.getMajor() != null ? student.getMajor() : "N/A");
            jLabel9.setText(String.format("%.2f", student.getGPA()));

            // Populate transcript table
            populateTranscriptTable();

            // Calculate and display REAL totals from completed courses
            int totalCredits = calculateTotalCredits();
            double cumulativeGPA = calculateCumulativeGPA();

            jLabel11.setText(String.valueOf(totalCredits));           // Total credits
            jLabel13.setText(String.format("%.2f", cumulativeGPA));   // Cumulative GPA
        }
    }
    private double calculateCumulativeGPA() {
        if (student == null || student.getCourses() == null) {
            return 0.0;
        }

        double totalQualityPoints = 0.0;
        int totalCredits = 0;

        for (Course course : student.getCourses()) {
            if (course.isCompleted()) { // Only completed courses count toward GPA
                totalQualityPoints += course.getQualityPoints();
                totalCredits += course.getCredits();
            }
        }

        return totalCredits > 0 ? totalQualityPoints / totalCredits : 0.0;
    }
    /**
     * Populate the transcript table with course data
     */
    private void populateTranscriptTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data
        
        if (student != null && student.getCoursesEnrolled() != null) {
            // Sample transcript data - in real system, this would come from completed courses
            Object[][] transcriptData = {
                {"Fall 2023", "Introduction to Programming", "CS101", "3", "A", "12.0"},
                {"Fall 2023", "Calculus I", "MATH201", "4", "A-", "14.8"},
                {"Fall 2023", "English Composition", "ENG101", "3", "B+", "9.9"},
                {"Spring 2024", "Data Structures", "CS102", "4", "B+", "13.2"},
                {"Spring 2024", "Physics I", "PHYS101", "4", "B", "12.0"},
                {"Spring 2024", "World History", "HIST101", "3", "A", "12.0"},
                {"Fall 2024", "Database Systems", "CS301", "3", "A", "12.0"},
                {"Fall 2024", "Linear Algebra", "MATH301", "3", "A-", "11.1"},
                {"Fall 2024", "Introduction to Psychology", "PSYC101", "3", "A", "12.0"}
            };
            
            for (Object[] row : transcriptData) {
                model.addRow(row);
            }
        }
    }
    
    /**
     * Calculate total credits from enrolled courses
     */
    private int calculateTotalCredits() {
        if (student == null || student.getCourses() == null) {
            return 0;
        }

        int totalCredits = 0;
        for (Course course : student.getCourses()) {
            if (course.isCompleted()) { // Only completed courses count
                totalCredits += course.getCredits();
            }
        }
        return totalCredits;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setText("<<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        jLabel1.setText("Transcript");

        jLabel2.setText("Student Name:");

        jLabel3.setText("jLabel3");

        jLabel4.setText("Major:");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Student ID:");

        jLabel7.setText("Current GPA:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "Course", "Code", "Credits", "Grade", "Points"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("Total:");

        jLabel11.setText("jLabel11");

        jLabel12.setText("Cum GPA:");

        jLabel13.setText("jLabel13");

        jButton2.setText("Update Grades");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Print Transcript");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(71, 71, 71)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jButton2)
                        .addGap(67, 67, 67)
                        .addComponent(jButton3)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (CardSequencePanel != null) {
            CardSequencePanel.removeAll();
            StudentWorkAreaJPanel studentWorkArea = new StudentWorkAreaJPanel(business, student, CardSequencePanel);
            CardSequencePanel.add("StudentWorkArea", studentWorkArea);
            ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "StudentWorkArea");
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(this, 
            "Please contact admin for updated grades.", 
            "Update Grades", 
            JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
