/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import Business.Profiles.StudentDirectory;
import javax.swing.JPanel;
import java.util.ArrayList;

/**
 *
    * @author Toluwalase Mebaanne
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel CardSequencePanel;
    private String currentFacultyId;

    /**
     * Creates new form PerformanceReportsJPanel
     */
    public PerformanceReportsJPanel() {
        initComponents();
        loadSampleData();
    }
    
    /**
     * Creates new form PerformanceReportsJPanel with Business and CardSequencePanel
     */
    public PerformanceReportsJPanel(Business b, JPanel clp, String facultyId) {
        business = b;
        this.CardSequencePanel = clp;
        this.currentFacultyId = facultyId;
        initComponents();
        setupEventHandlers();
        loadPerformanceData();
    }
    
    /**
     * Setup event handlers
     */
    private void setupEventHandlers() {
        jButton1.addActionListener(e -> goBack());
    }
    
    /**
     * Load performance data from the business layer
     */
    private void loadPerformanceData() {
        if (business != null) {
            try {
                StudentDirectory studentDirectory = business.getStudentDirectory();
                if (studentDirectory != null) {
                    ArrayList<StudentProfile> studentList = studentDirectory.getStudentList();
                    
                    // Calculate total students
                    int totalStudents = studentList.size();
                    
                    // Calculate average GPA
                    double totalGPA = 0.0;
                    int studentsWithGPA = 0;
                    
                    for (StudentProfile student : studentList) {
                        if (student != null && student.getGPA() > 0) {
                            totalGPA += student.getGPA();
                            studentsWithGPA++;
                        }
                    }
                    
                    double averageGPA = studentsWithGPA > 0 ? totalGPA / studentsWithGPA : 0.0;
                    
                    // Update the labels with calculated values
                    jLabel7.setText(String.valueOf(totalStudents));
                    jLabel8.setText(String.format("%.2f", averageGPA));
                    
                } else {
                    // No student data available
                    jLabel7.setText("0");
                    jLabel8.setText("0.00");
                }
            } catch (Exception e) {
                // Error loading data, show defaults
                jLabel7.setText("0");
                jLabel8.setText("0.00");
                System.out.println("Error loading performance data: " + e.getMessage());
            }
        } else {
            // No business layer, show sample data
            loadSampleData();
        }
    }
    
    /**
     * Load sample data when no business layer
     */
    private void loadSampleData() {
        jLabel7.setText("3");
        jLabel8.setText("3.45");
    }
    
    /**
     * Go back to Faculty Work Area
     */
    private void goBack() {
        if (CardSequencePanel != null) {
            CardSequencePanel.removeAll();
            FacultyWorkAreaJPanel facultyWorkArea = new FacultyWorkAreaJPanel(business, CardSequencePanel, currentFacultyId);
            CardSequencePanel.add("FacultyWorkArea", facultyWorkArea);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "FacultyWorkArea");
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        jButton1.setText("<<< Back");

        jLabel1.setFont(new java.awt.Font("Lao MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Performance Reports");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metric");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Students:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Average Student GPA:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Value");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addContainerGap(544, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
