/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yasminalmousa
 */
public class SignUpJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel cardSequencePanel;

    /**
     * Creates new form SignUpJPanel with business logic
     */
    public SignUpJPanel(Business business, JPanel cardSequencePanel) {
        this.business = business;
        this.cardSequencePanel = cardSequencePanel;
        initComponents();
    }

    /**
     * Creates new form SignUpJPanel (default constructor)
     */
    public SignUpJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        fieldFullName = new javax.swing.JTextField();
        fieldNUID = new javax.swing.JTextField();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        fieldEmail = new javax.swing.JTextField();
        fieldMajor = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        jLabel1.setText("Student Sign Up");

        jLabel2.setText("Full Name:");

        jLabel3.setText("NUID:");

        jLabel4.setText("Username:");

        jLabel5.setText("Password:");

        jLabel6.setText("Email:");

        jLabel7.setText("Major:");

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        fieldPassword.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldFullName)
                    .addComponent(fieldNUID)
                    .addComponent(fieldUsername)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(fieldEmail)
                    .addComponent(fieldMajor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignUp)
                    .addComponent(jLabel1))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnSignUp)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
    if (!validateInput()) {
            return;
        }

        String fullName = fieldFullName.getText().trim();
        String nuid = fieldNUID.getText().trim();
        String username = fieldUsername.getText().trim();
        String password = new String(fieldPassword.getPassword());
        String email = fieldEmail.getText().trim();
        String major = fieldMajor.getText().trim();

        try {
            // Check if username already exists
            UserAccountDirectory uad = business.getUserAccountDirectory();
            for (UserAccount ua : uad.getUserAccountList()) {
                if (ua.getUserLoginName().equalsIgnoreCase(username)) {
                    JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.", 
                                                "Registration Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Check if NUID is already registered
            StudentDirectory sd = business.getStudentDirectory();
            for (StudentProfile sp : sd.getStudentList()) {
                if (sp.getNuid() != null && sp.getNuid().equals(nuid)) {
                    JOptionPane.showMessageDialog(this, "NUID is already registered.", 
                                                "Registration Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Create new person
            PersonDirectory pd = business.getPersonDirectory();
            Person newPerson = pd.newPersonWithName(fullName);

            // Create new student profile
            StudentProfile newStudent = sd.newStudentProfile(newPerson, nuid);
            newStudent.setEmail(email);
            newStudent.setMajor(major);
            newStudent.setAcademicLevel("Undergraduate"); // Default

            // Create user account
            UserAccount newAccount = uad.newUserAccount(newStudent, username, password);

            JOptionPane.showMessageDialog(this, "Registration successful! You can now log in with your credentials.", 
                                        "Registration Complete", JOptionPane.INFORMATION_MESSAGE);

            // Clear fields
            clearFields();

            // Go back to login screen
            if (cardSequencePanel != null) {
                cardSequencePanel.remove(this);
                ((java.awt.CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Registration failed: " + e.getMessage(), "Registration Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cardSequencePanel != null) {
            cardSequencePanel.remove(this);
            ((java.awt.CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void clearFields() {
        fieldFullName.setText("");
        fieldNUID.setText("");
        fieldUsername.setText("");
        fieldPassword.setText("");
        fieldEmail.setText("");
        fieldMajor.setText("");
    }
    private boolean validateInput() {
        // Check if any required field is empty
        if (fieldFullName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Full name is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldFullName.requestFocus();
            return false;
        }

        if (fieldNUID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NUID is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldNUID.requestFocus();
            return false;
        }

        if (fieldUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldUsername.requestFocus();
            return false;
        }

        if (fieldPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Password is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldPassword.requestFocus();
            return false;
        }

        if (fieldEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldEmail.requestFocus();
            return false;
        }

        // Basic NUID validation (should be 9 digits)
        String nuid = fieldNUID.getText().trim();
        if (!nuid.matches("\\d{9}")) {
            JOptionPane.showMessageDialog(this, "NUID must be exactly 9 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldNUID.requestFocus();
            return false;
        }

        // Basic email validation
        String email = fieldEmail.getText().trim();
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldEmail.requestFocus();
            return false;
        }

        // Password length validation
        if (fieldPassword.getPassword().length < 4) {
            JOptionPane.showMessageDialog(this, "Password must be at least 4 characters long.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            fieldPassword.requestFocus();
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFullName;
    private javax.swing.JTextField fieldMajor;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
